# Generated by Django 6.0.2 on 2026-03-05 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отписки')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('never', 'Никогда')], default='daily', max_length=20, verbose_name='Частота')),
                ('categories', models.ManyToManyField(blank=True, to='news.category', verbose_name='Категории')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': 'Подписки на рассылку',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
